### ISSUE TITLE
Readers and Writers not closed

### ISSUE THREAD

**Issue by swopl** [magley/sims-tollbooth#20]
In a lof of places, these aren't closed. These don't close automatically on end of function in Java. It is undefined when the GC will catch and close them. So you should close them when you are done using them. You can use try-with-resources construct if you want, this one closes automatically on end of block

**Comment by filipkontic** [comment]
This solution isn't good. Manually closing resources doesn't account for exception-induced codepaths. Consider this code:
```java
try {
    Reader reader = new BufferedReader(new FileReader(new File(fullpath)));
    xstream.fromXML(reader, this);
    reader.close();
} catch (XStreamException e) {
    // do something
}
```
What happens if `xstream.fromXML(reader, this)` throws? We will never reach `reader.close()` as we continue execution in the catch block. Using try-with-resources is therefore not a preference, but the objectively correct solution.
